import {
	cancellationCreateDescription,
	cancellationCreateExecute,
	cancellationCreateInput,
	cancellationEligibilityDescription,
	cancellationEligibilityExecute,
	cancellationEligibilityInput,
	disputesActivityDescription,
	disputesActivityExecute,
	disputesActivityInput,
	disputesGetDescription,
	disputesGetExecute,
	disputesGetInput,
	disputesListDescription,
	disputesListExecute,
	disputesListInput,
	disputesRespondDescription,
	disputesRespondExecute,
	disputesRespondInput,
} from "../disputes.js";
import {
	feedbackAwaitingDescription,
	feedbackAwaitingExecute,
	feedbackAwaitingInput,
	feedbackLeaveDescription,
	feedbackLeaveExecute,
	feedbackLeaveInput,
	feedbackListDescription,
	feedbackListExecute,
	feedbackListInput,
} from "../feedback.js";
import {
	conversationsListDescription,
	conversationsListExecute,
	conversationsListInput,
	conversationThreadDescription,
	conversationThreadExecute,
	conversationThreadInput,
	messagesSendDescription,
	messagesSendExecute,
	messagesSendInput,
} from "../messages.js";
import {
	offersCreateDescription,
	offersCreateExecute,
	offersCreateInput,
	offersEligibleListingsDescription,
	offersEligibleListingsExecute,
	offersEligibleListingsInput,
	offersListDescription,
	offersListExecute,
	offersListInput,
	offersRespondDescription,
	offersRespondExecute,
	offersRespondInput,
} from "../offers.js";
import type { Tool } from "../registry.js";

// Post-sale buyer turnover: messages, offers, disputes, cancellations, feedback.
export const commsTools: Tool[] = [
	{
		name: "flipagent_list_conversations",
		description: conversationsListDescription,
		inputSchema: conversationsListInput,
		execute: conversationsListExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_get_conversation_thread",
		description: conversationThreadDescription,
		inputSchema: conversationThreadInput,
		execute: conversationThreadExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_send_message",
		description: messagesSendDescription,
		inputSchema: messagesSendInput,
		execute: messagesSendExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_offers",
		description: offersListDescription,
		inputSchema: offersListInput,
		execute: offersListExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_create_offer",
		description: offersCreateDescription,
		inputSchema: offersCreateInput,
		execute: offersCreateExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_offer_eligible_listings",
		description: offersEligibleListingsDescription,
		inputSchema: offersEligibleListingsInput,
		execute: offersEligibleListingsExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_respond_to_offer",
		description: offersRespondDescription,
		inputSchema: offersRespondInput,
		execute: offersRespondExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_disputes",
		description: disputesListDescription,
		inputSchema: disputesListInput,
		execute: disputesListExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_get_dispute",
		description: disputesGetDescription,
		inputSchema: disputesGetInput,
		execute: disputesGetExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_respond_to_dispute",
		description: disputesRespondDescription,
		inputSchema: disputesRespondInput,
		execute: disputesRespondExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_get_dispute_activity",
		description: disputesActivityDescription,
		inputSchema: disputesActivityInput,
		execute: disputesActivityExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_check_cancellation_eligibility",
		description: cancellationEligibilityDescription,
		inputSchema: cancellationEligibilityInput,
		execute: cancellationEligibilityExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_create_cancellation",
		description: cancellationCreateDescription,
		inputSchema: cancellationCreateInput,
		execute: cancellationCreateExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_feedback",
		description: feedbackListDescription,
		inputSchema: feedbackListInput,
		execute: feedbackListExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_awaiting_feedback",
		description: feedbackAwaitingDescription,
		inputSchema: feedbackAwaitingInput,
		execute: feedbackAwaitingExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_leave_feedback",
		description: feedbackLeaveDescription,
		inputSchema: feedbackLeaveInput,
		execute: feedbackLeaveExecute,
		toolset: "comms",
	},
];
