import {
	bidsCancelDescription,
	bidsCancelExecute,
	bidsCancelInput,
	bidsGetStatusDescription,
	bidsGetStatusExecute,
	bidsGetStatusInput,
	bidsListDescription,
	bidsListExecute,
	bidsListInput,
	bidsPlaceDescription,
	bidsPlaceExecute,
	bidsPlaceInput,
} from "../bids.js";
import {
	ebayBuyItemDescription,
	ebayBuyItemExecute,
	ebayBuyItemInput,
	ebayOrderCancelDescription,
	ebayOrderCancelExecute,
	ebayOrderCancelInput,
	ebayOrderStatusDescription,
	ebayOrderStatusExecute,
	ebayOrderStatusInput,
	purchasesListDescription,
	purchasesListExecute,
	purchasesListInput,
} from "../ebay-buy.js";
import { ebayItemDetailDescription, ebayItemDetailExecute, ebayItemDetailInput } from "../ebay-item-detail.js";
import {
	ebayCreateInventoryItemDescription,
	ebayCreateInventoryItemExecute,
	ebayCreateInventoryItemInput,
	ebayCreateOfferDescription,
	ebayCreateOfferExecute,
	ebayCreateOfferInput,
	ebayPublishOfferDescription,
	ebayPublishOfferExecute,
	ebayPublishOfferInput,
	listingsBulkPublishDescription,
	listingsBulkPublishExecute,
	listingsBulkPublishInput,
	listingsBulkUpdatePricesDescription,
	listingsBulkUpdatePricesExecute,
	listingsBulkUpdatePricesInput,
	listingsCreateDraftDescription,
	listingsCreateDraftExecute,
	listingsCreateDraftInput,
	listingsEndDescription,
	listingsEndExecute,
	listingsEndInput,
	listingsGetDescription,
	listingsGetExecute,
	listingsGetInput,
	listingsGroupPublishDescription,
	listingsGroupPublishExecute,
	listingsGroupPublishInput,
	listingsGroupWithdrawDescription,
	listingsGroupWithdrawExecute,
	listingsGroupWithdrawInput,
	listingsListDescription,
	listingsListExecute,
	listingsListInput,
} from "../ebay-listings.js";
import { ebayListPayoutsDescription, ebayListPayoutsExecute, ebayListPayoutsInput } from "../ebay-payouts.js";
import {
	ebayListOrdersDescription,
	ebayListOrdersExecute,
	ebayListOrdersInput,
	ebayMarkShippedDescription,
	ebayMarkShippedExecute,
	ebayMarkShippedInput,
} from "../ebay-sales.js";
import { ebaySearchDescription, ebaySearchExecute, ebaySearchInput } from "../ebay-search.js";
import { ebaySoldSearchDescription, ebaySoldSearchExecute, ebaySoldSearchInput } from "../ebay-sold-search.js";
import {
	ebayTaxonomyAspectsDescription,
	ebayTaxonomyAspectsExecute,
	ebayTaxonomyAspectsInput,
	ebayTaxonomyDefaultIdDescription,
	ebayTaxonomyDefaultIdExecute,
	ebayTaxonomyDefaultIdInput,
	ebayTaxonomySuggestDescription,
	ebayTaxonomySuggestExecute,
	ebayTaxonomySuggestInput,
} from "../ebay-taxonomy.js";
import {
	evaluateJobDescription,
	evaluateJobExecute,
	evaluateJobInput,
	evaluateListingDescription,
	evaluateListingExecute,
	evaluateListingInput,
	evaluationPoolDescription,
	evaluationPoolExecute,
	evaluationPoolInput,
} from "../evaluate-listing.js";
import {
	flipagentCapabilitiesDescription,
	flipagentCapabilitiesExecute,
	flipagentCapabilitiesInput,
} from "../flipagent-capabilities.js";
import {
	flipagentConnectStatusDescription,
	flipagentConnectStatusExecute,
	flipagentConnectStatusInput,
} from "../flipagent-connect.js";
import { keysMeDescription, keysMeExecute, keysMeInput } from "../keys.js";
import {
	listingsPreviewFeesDescription,
	listingsPreviewFeesExecute,
	listingsPreviewFeesInput,
} from "../listings-fees.js";
import {
	locationsListDescription,
	locationsListExecute,
	locationsListInput,
	locationsUpsertDescription,
	locationsUpsertExecute,
	locationsUpsertInput,
} from "../locations.js";
import {
	mePrograms_listDescription,
	mePrograms_listExecute,
	mePrograms_listInput,
	mePrograms_optInDescription,
	mePrograms_optInExecute,
	mePrograms_optInInput,
	mePrograms_optOutDescription,
	mePrograms_optOutExecute,
	mePrograms_optOutInput,
	meQuotaDescription,
	meQuotaExecute,
	meQuotaInput,
} from "../me-account.js";
import {
	ebayPictureUploadDescription,
	ebayPictureUploadExecute,
	ebayPictureUploadInput,
	mediaCreateUploadDescription,
	mediaCreateUploadExecute,
	mediaCreateUploadInput,
	mediaGetDescription,
	mediaGetExecute,
	mediaGetInput,
} from "../media.js";
import {
	policiesListByTypeDescription,
	policiesListByTypeExecute,
	policiesListByTypeInput,
	policiesListDescription,
	policiesListExecute,
	policiesListInput,
	sellerPoliciesSetupDescription,
	sellerPoliciesSetupExecute,
	sellerPoliciesSetupInput,
} from "../policies.js";
import {
	recommendationsListDescription,
	recommendationsListExecute,
	recommendationsListInput,
} from "../recommendations.js";
import type { Tool } from "../registry.js";
import { shipQuoteDescription, shipQuoteExecute, shipQuoteInput } from "../ship-quote.js";
import { transactionsListDescription, transactionsListExecute, transactionsListInput } from "../transactions.js";

export const coreTools: Tool[] = [
	// First-call discovery + key introspection.
	{
		name: "flipagent_get_capabilities",
		description: flipagentCapabilitiesDescription,
		inputSchema: flipagentCapabilitiesInput,
		execute: flipagentCapabilitiesExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_my_key",
		description: keysMeDescription,
		inputSchema: keysMeInput,
		execute: keysMeExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_quota",
		description: meQuotaDescription,
		inputSchema: meQuotaInput,
		execute: meQuotaExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_programs",
		description: mePrograms_listDescription,
		inputSchema: mePrograms_listInput,
		execute: mePrograms_listExecute,
		toolset: "core",
	},
	{
		name: "flipagent_opt_in_program",
		description: mePrograms_optInDescription,
		inputSchema: mePrograms_optInInput,
		execute: mePrograms_optInExecute,
		toolset: "core",
	},
	{
		name: "flipagent_opt_out_program",
		description: mePrograms_optOutDescription,
		inputSchema: mePrograms_optOutInput,
		execute: mePrograms_optOutExecute,
		toolset: "core",
	},

	// Sourcing — marketplace data (no eBay OAuth needed)
	{
		name: "flipagent_search_items",
		description: ebaySearchDescription,
		inputSchema: ebaySearchInput,
		execute: ebaySearchExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_item",
		description: ebayItemDetailDescription,
		inputSchema: ebayItemDetailInput,
		execute: ebayItemDetailExecute,
		toolset: "core",
	},
	{
		name: "flipagent_search_sold_items",
		description: ebaySoldSearchDescription,
		inputSchema: ebaySoldSearchInput,
		execute: ebaySoldSearchExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_categories",
		description: ebayTaxonomyDefaultIdDescription,
		inputSchema: ebayTaxonomyDefaultIdInput,
		execute: ebayTaxonomyDefaultIdExecute,
		toolset: "core",
	},
	{
		name: "flipagent_suggest_category",
		description: ebayTaxonomySuggestDescription,
		inputSchema: ebayTaxonomySuggestInput,
		execute: ebayTaxonomySuggestExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_category_aspects",
		description: ebayTaxonomyAspectsDescription,
		inputSchema: ebayTaxonomyAspectsInput,
		execute: ebayTaxonomyAspectsExecute,
		toolset: "core",
	},

	// Decisions + Operations — flipagent value-add
	{
		name: "flipagent_evaluate_item",
		description: evaluateListingDescription,
		inputSchema: evaluateListingInput,
		execute: evaluateListingExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_evaluate_job",
		description: evaluateJobDescription,
		inputSchema: evaluateJobInput,
		execute: evaluateJobExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_evaluation_pool",
		description: evaluationPoolDescription,
		inputSchema: evaluationPoolInput,
		execute: evaluationPoolExecute,
		toolset: "core",
	},
	{
		name: "flipagent_quote_shipping",
		description: shipQuoteDescription,
		inputSchema: shipQuoteInput,
		execute: shipQuoteExecute,
		toolset: "core",
	},

	// Buying (extension-bridged or REST passthrough)
	{
		name: "flipagent_create_purchase",
		description: ebayBuyItemDescription,
		inputSchema: ebayBuyItemInput,
		execute: ebayBuyItemExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_purchases",
		description: purchasesListDescription,
		inputSchema: purchasesListInput,
		execute: purchasesListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_purchase",
		description: ebayOrderStatusDescription,
		inputSchema: ebayOrderStatusInput,
		execute: ebayOrderStatusExecute,
		toolset: "core",
	},
	{
		name: "flipagent_cancel_purchase",
		description: ebayOrderCancelDescription,
		inputSchema: ebayOrderCancelInput,
		execute: ebayOrderCancelExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_bids",
		description: bidsListDescription,
		inputSchema: bidsListInput,
		execute: bidsListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_place_bid",
		description: bidsPlaceDescription,
		inputSchema: bidsPlaceInput,
		execute: bidsPlaceExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_bid_status",
		description: bidsGetStatusDescription,
		inputSchema: bidsGetStatusInput,
		execute: bidsGetStatusExecute,
		toolset: "core",
	},
	{
		name: "flipagent_cancel_bid",
		description: bidsCancelDescription,
		inputSchema: bidsCancelInput,
		execute: bidsCancelExecute,
		toolset: "core",
	},

	// Listing prereqs + listing CRUD (sell-side, eBay OAuth required)
	{
		name: "flipagent_upload_image_to_ebay",
		description: ebayPictureUploadDescription,
		inputSchema: ebayPictureUploadInput,
		execute: ebayPictureUploadExecute,
		toolset: "core",
	},
	{
		name: "flipagent_create_media_upload",
		description: mediaCreateUploadDescription,
		inputSchema: mediaCreateUploadInput,
		execute: mediaCreateUploadExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_media",
		description: mediaGetDescription,
		inputSchema: mediaGetInput,
		execute: mediaGetExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_policies",
		description: policiesListDescription,
		inputSchema: policiesListInput,
		execute: policiesListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_policies_by_type",
		description: policiesListByTypeDescription,
		inputSchema: policiesListByTypeInput,
		execute: policiesListByTypeExecute,
		toolset: "core",
	},
	{
		name: "flipagent_create_seller_policies",
		description: sellerPoliciesSetupDescription,
		inputSchema: sellerPoliciesSetupInput,
		execute: sellerPoliciesSetupExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_locations",
		description: locationsListDescription,
		inputSchema: locationsListInput,
		execute: locationsListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_upsert_location",
		description: locationsUpsertDescription,
		inputSchema: locationsUpsertInput,
		execute: locationsUpsertExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_listings",
		description: listingsListDescription,
		inputSchema: listingsListInput,
		execute: listingsListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_listing",
		description: listingsGetDescription,
		inputSchema: listingsGetInput,
		execute: listingsGetExecute,
		toolset: "core",
	},
	{
		name: "flipagent_create_listing",
		description: ebayCreateInventoryItemDescription,
		inputSchema: ebayCreateInventoryItemInput,
		execute: ebayCreateInventoryItemExecute,
		toolset: "core",
	},
	{
		name: "flipagent_create_draft_listing",
		description: listingsCreateDraftDescription,
		inputSchema: listingsCreateDraftInput,
		execute: listingsCreateDraftExecute,
		toolset: "core",
	},
	{
		name: "flipagent_update_listing",
		description: ebayCreateOfferDescription,
		inputSchema: ebayCreateOfferInput,
		execute: ebayCreateOfferExecute,
		toolset: "core",
	},
	{
		name: "flipagent_bulk_update_listing_prices",
		description: listingsBulkUpdatePricesDescription,
		inputSchema: listingsBulkUpdatePricesInput,
		execute: listingsBulkUpdatePricesExecute,
		toolset: "core",
	},
	{
		name: "flipagent_end_listing",
		description: listingsEndDescription,
		inputSchema: listingsEndInput,
		execute: listingsEndExecute,
		toolset: "core",
	},
	{
		name: "flipagent_relist_listing",
		description: ebayPublishOfferDescription,
		inputSchema: ebayPublishOfferInput,
		execute: ebayPublishOfferExecute,
		toolset: "core",
	},
	{
		name: "flipagent_bulk_publish_listings",
		description: listingsBulkPublishDescription,
		inputSchema: listingsBulkPublishInput,
		execute: listingsBulkPublishExecute,
		toolset: "core",
	},
	{
		name: "flipagent_publish_listing_group",
		description: listingsGroupPublishDescription,
		inputSchema: listingsGroupPublishInput,
		execute: listingsGroupPublishExecute,
		toolset: "core",
	},
	{
		name: "flipagent_withdraw_listing_group",
		description: listingsGroupWithdrawDescription,
		inputSchema: listingsGroupWithdrawInput,
		execute: listingsGroupWithdrawExecute,
		toolset: "core",
	},
	{
		name: "flipagent_preview_listing_fees",
		description: listingsPreviewFeesDescription,
		inputSchema: listingsPreviewFeesInput,
		execute: listingsPreviewFeesExecute,
		toolset: "core",
	},

	// Sale fulfillment + finance (sell-side)
	{
		name: "flipagent_list_sales",
		description: ebayListOrdersDescription,
		inputSchema: ebayListOrdersInput,
		execute: ebayListOrdersExecute,
		toolset: "core",
	},
	{
		name: "flipagent_ship_sale",
		description: ebayMarkShippedDescription,
		inputSchema: ebayMarkShippedInput,
		execute: ebayMarkShippedExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_payouts",
		description: ebayListPayoutsDescription,
		inputSchema: ebayListPayoutsInput,
		execute: ebayListPayoutsExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_transactions",
		description: transactionsListDescription,
		inputSchema: transactionsListInput,
		execute: transactionsListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_recommendations",
		description: recommendationsListDescription,
		inputSchema: recommendationsListInput,
		execute: recommendationsListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_ebay_connection",
		description: flipagentConnectStatusDescription,
		inputSchema: flipagentConnectStatusInput,
		execute: flipagentConnectStatusExecute,
		toolset: "core",
	},
];
