import {
	planetExpressGetAddressDescription,
	planetExpressGetAddressExecute,
	planetExpressGetAddressInput,
	planetExpressInventoryDescription,
	planetExpressInventoryExecute,
	planetExpressInventoryInput,
	planetExpressJobStatusDescription,
	planetExpressJobStatusExecute,
	planetExpressJobStatusInput,
	planetExpressLinkDescription,
	planetExpressLinkExecute,
	planetExpressLinkInput,
	planetExpressPackageDispatchDescription,
	planetExpressPackageDispatchExecute,
	planetExpressPackageDispatchInput,
	planetExpressPackagePhotosDescription,
	planetExpressPackagePhotosExecute,
	planetExpressPackagePhotosInput,
	planetExpressPackagesDescription,
	planetExpressPackagesExecute,
	planetExpressPackagesInput,
} from "../forwarder-planetexpress.js";
import type { Tool } from "../registry.js";

export const forwarderTools: Tool[] = [
	{
		name: "flipagent_refresh_forwarder",
		description: planetExpressPackagesDescription,
		inputSchema: planetExpressPackagesInput,
		execute: planetExpressPackagesExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_list_forwarder_inventory",
		description: planetExpressInventoryDescription,
		inputSchema: planetExpressInventoryInput,
		execute: planetExpressInventoryExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_request_package_photos",
		description: planetExpressPackagePhotosDescription,
		inputSchema: planetExpressPackagePhotosInput,
		execute: planetExpressPackagePhotosExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_dispatch_package",
		description: planetExpressPackageDispatchDescription,
		inputSchema: planetExpressPackageDispatchInput,
		execute: planetExpressPackageDispatchExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_link_package",
		description: planetExpressLinkDescription,
		inputSchema: planetExpressLinkInput,
		execute: planetExpressLinkExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_get_forwarder_job",
		description: planetExpressJobStatusDescription,
		inputSchema: planetExpressJobStatusInput,
		execute: planetExpressJobStatusExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_get_forwarder_address",
		description: planetExpressGetAddressDescription,
		inputSchema: planetExpressGetAddressInput,
		execute: planetExpressGetAddressExecute,
		toolset: "forwarder",
	},
];
