import {
	notificationsConfigGetDescription,
	notificationsConfigGetExecute,
	notificationsConfigGetInput,
	notificationsConfigUpdateDescription,
	notificationsConfigUpdateExecute,
	notificationsConfigUpdateInput,
	notificationsDestinationsDescription,
	notificationsDestinationsExecute,
	notificationsDestinationsInput,
	notificationsPublicKeyDescription,
	notificationsPublicKeyExecute,
	notificationsPublicKeyInput,
	notificationsRecentDescription,
	notificationsRecentExecute,
	notificationsRecentInput,
	notificationsSubAddFilterDescription,
	notificationsSubAddFilterExecute,
	notificationsSubAddFilterInput,
	notificationsSubDeleteFilterDescription,
	notificationsSubDeleteFilterExecute,
	notificationsSubDeleteFilterInput,
	notificationsSubDisableDescription,
	notificationsSubDisableExecute,
	notificationsSubDisableInput,
	notificationsSubEnableDescription,
	notificationsSubEnableExecute,
	notificationsSubEnableInput,
	notificationsSubscriptionsCreateDescription,
	notificationsSubscriptionsCreateExecute,
	notificationsSubscriptionsCreateInput,
	notificationsSubscriptionsDeleteDescription,
	notificationsSubscriptionsDeleteExecute,
	notificationsSubscriptionsDeleteInput,
	notificationsSubscriptionsGetDescription,
	notificationsSubscriptionsGetExecute,
	notificationsSubscriptionsGetInput,
	notificationsSubscriptionsListDescription,
	notificationsSubscriptionsListExecute,
	notificationsSubscriptionsListInput,
	notificationsSubTestDescription,
	notificationsSubTestExecute,
	notificationsSubTestInput,
	notificationsTopicsDescription,
	notificationsTopicsExecute,
	notificationsTopicsInput,
} from "../notifications.js";
import type { Tool } from "../registry.js";
import {
	webhooksListDescription,
	webhooksListExecute,
	webhooksListInput,
	webhooksRegisterDescription,
	webhooksRegisterExecute,
	webhooksRegisterInput,
	webhooksRevokeDescription,
	webhooksRevokeExecute,
	webhooksRevokeInput,
} from "../webhooks.js";

// Outgoing webhooks (flipagent → user) + eBay platform notifications.
export const notificationsTools: Tool[] = [
	{
		name: "flipagent_register_webhook",
		description: webhooksRegisterDescription,
		inputSchema: webhooksRegisterInput,
		execute: webhooksRegisterExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_webhooks",
		description: webhooksListDescription,
		inputSchema: webhooksListInput,
		execute: webhooksListExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_revoke_webhook",
		description: webhooksRevokeDescription,
		inputSchema: webhooksRevokeInput,
		execute: webhooksRevokeExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_notification_topics",
		description: notificationsTopicsDescription,
		inputSchema: notificationsTopicsInput,
		execute: notificationsTopicsExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_notification_destinations",
		description: notificationsDestinationsDescription,
		inputSchema: notificationsDestinationsInput,
		execute: notificationsDestinationsExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_notification_subscriptions",
		description: notificationsSubscriptionsListDescription,
		inputSchema: notificationsSubscriptionsListInput,
		execute: notificationsSubscriptionsListExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_create_notification_subscription",
		description: notificationsSubscriptionsCreateDescription,
		inputSchema: notificationsSubscriptionsCreateInput,
		execute: notificationsSubscriptionsCreateExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_get_notification_subscription",
		description: notificationsSubscriptionsGetDescription,
		inputSchema: notificationsSubscriptionsGetInput,
		execute: notificationsSubscriptionsGetExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_delete_notification_subscription",
		description: notificationsSubscriptionsDeleteDescription,
		inputSchema: notificationsSubscriptionsDeleteInput,
		execute: notificationsSubscriptionsDeleteExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_enable_notification_subscription",
		description: notificationsSubEnableDescription,
		inputSchema: notificationsSubEnableInput,
		execute: notificationsSubEnableExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_disable_notification_subscription",
		description: notificationsSubDisableDescription,
		inputSchema: notificationsSubDisableInput,
		execute: notificationsSubDisableExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_test_notification_subscription",
		description: notificationsSubTestDescription,
		inputSchema: notificationsSubTestInput,
		execute: notificationsSubTestExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_add_notification_filter",
		description: notificationsSubAddFilterDescription,
		inputSchema: notificationsSubAddFilterInput,
		execute: notificationsSubAddFilterExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_delete_notification_filter",
		description: notificationsSubDeleteFilterDescription,
		inputSchema: notificationsSubDeleteFilterInput,
		execute: notificationsSubDeleteFilterExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_get_notification_config",
		description: notificationsConfigGetDescription,
		inputSchema: notificationsConfigGetInput,
		execute: notificationsConfigGetExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_update_notification_config",
		description: notificationsConfigUpdateDescription,
		inputSchema: notificationsConfigUpdateInput,
		execute: notificationsConfigUpdateExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_get_notification_public_key",
		description: notificationsPublicKeyDescription,
		inputSchema: notificationsPublicKeyInput,
		execute: notificationsPublicKeyExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_recent_notifications",
		description: notificationsRecentDescription,
		inputSchema: notificationsRecentInput,
		execute: notificationsRecentExecute,
		toolset: "notifications",
	},
];
