/**
 * GET / — service descriptor. Open (no key needed). Useful for liveness probes
 * and as a quick "is this api.flipagent.dev" check from a browser.
 */

import { RootDescriptor } from "@flipagent/types";
import { Hono } from "hono";
import { describeRoute } from "hono-openapi";
import { jsonResponse } from "../utils/openapi.js";

export const rootRoute = new Hono();

rootRoute.get(
	"/",
	describeRoute({
		tags: ["System"],
		summary: "Service descriptor",
		security: [],
		responses: {
			200: jsonResponse("Manifest of available paths.", RootDescriptor),
		},
	}),
	(c) =>
		c.json({
			name: "flipagent",
			docs: "https://flipagent.dev/docs",
			ebay_compatible: false,
			paths: [
				// Marketplace data (read) — anonymous app token
				"GET /v1/items/search",
				"GET /v1/items/{id}",
				"GET /v1/categories",
				"GET /v1/categories/suggest",
				"GET /v1/categories/item-aspects",
				"GET /v1/categories/{id}/aspects",
				"GET /v1/categories/{id}/compatibility-properties",
				"GET /v1/products/search",
				"GET /v1/products/metadata",
				"GET /v1/products/category-metadata",
				"GET /v1/products/{epid}",
				"GET /v1/media/{id}",
				"POST /v1/media/uploads",
				"POST /v1/media/ebay-pictures",
				"POST /v1/items/check-compatibility",
				"POST /v1/items/search-by-image",
				// Buy + Receive
				"POST /v1/purchases",
				"GET /v1/purchases",
				"GET /v1/purchases/{id}",
				"PATCH /v1/purchases/{id}/shipping",
				"PATCH /v1/purchases/{id}/payment",
				"PATCH|DELETE /v1/purchases/{id}/coupon",
				"POST /v1/purchases/{id}/cancel",
				"ALL /v1/bids/*",
				"POST /v1/forwarder/{provider}/refresh",
				"POST /v1/forwarder/{provider}/address",
				"GET /v1/forwarder/{provider}/inventory",
				"GET /v1/forwarder/{provider}/inventory/{packageId}",
				"POST /v1/forwarder/{provider}/packages/{packageId}/photos",
				"POST /v1/forwarder/{provider}/packages/{packageId}/link",
				"POST /v1/forwarder/{provider}/packages/{packageId}/dispatch",
				"GET /v1/forwarder/{provider}/jobs/{jobId}",
				// Sell-side write (eBay OAuth)
				"POST /v1/listings",
				"POST /v1/listings/verify",
				"POST /v1/listings/draft",
				"POST /v1/listings/preview-fees",
				"GET /v1/listings",
				"GET|PATCH|DELETE /v1/listings/{sku}",
				"POST /v1/listings/{sku}/relist",
				"GET|PUT|DELETE /v1/listings/{sku}/compatibility",
				"GET|PUT|DELETE /v1/listings/{listingId}/skus/{sku}/locations",
				"POST /v1/listings/groups/{groupKey}/publish",
				"POST /v1/listings/groups/{groupKey}/withdraw",
				"ALL /v1/locations/*",
				"GET /v1/policies",
				"GET /v1/policies/by-name",
				"GET /v1/policies/rate-tables",
				"GET|POST /v1/policies/custom",
				"POST /v1/policies/setup",
				"POST /v1/policies/{id}/transfer",
				"POST /v1/policies",
				"PUT|DELETE /v1/policies/{type}/{id}",
				"GET /v1/sales",
				"GET /v1/sales/{id}",
				"POST /v1/sales/{id}/ship",
				"POST /v1/sales/{id}/refund",
				"ALL /v1/labels/*",
				// Money + comms + disputes (eBay OAuth)
				"GET /v1/payouts",
				"GET /v1/payouts/summary",
				"GET /v1/transactions",
				"GET /v1/messages",
				"POST /v1/messages",
				"GET /v1/messages/{conversationId}",
				"PATCH /v1/messages/conversations/bulk",
				"PATCH /v1/messages/conversations/{id}",
				"GET /v1/offers",
				"POST /v1/offers",
				"GET /v1/offers/eligible-listings",
				"POST /v1/offers/{id}/respond",
				"GET /v1/feedback",
				"POST /v1/feedback",
				"GET /v1/feedback/awaiting",
				"POST /v1/feedback/{id}/respond",
				"GET /v1/disputes",
				"GET /v1/disputes/{id}",
				"GET /v1/disputes/{id}/activity",
				"POST /v1/disputes/{id}/respond",
				"POST /v1/disputes/{id}/close",
				"POST /v1/disputes/{id}/evidence",
				"PUT /v1/disputes/{id}/evidence/{evidenceId}",
				"POST /v1/disputes/{id}/evidence/files",
				"GET /v1/disputes/{id}/evidence/{evidenceId}/files/{fileId}",
				"POST /v1/disputes/cancellations",
				"POST /v1/disputes/cancellations/check-eligibility",
				"GET /v1/recommendations",
				"ALL /v1/analytics/*",
				// flipagent: evaluate (Decisions pillar) — sync POST + queue-backed
				// async create / poll / SSE stream / cancel. Tab close mid-run keeps
				// the worker running.
				"POST /v1/evaluate",
				"POST /v1/evaluate/jobs",
				"GET /v1/evaluate/jobs/{id}",
				"GET /v1/evaluate/jobs/{id}/stream",
				"POST /v1/evaluate/jobs/{id}/cancel",
				"GET /v1/evaluate/featured",
				"GET /v1/evaluate/active",
				"GET /v1/evaluate/{itemId}/pool",
				// flipagent: ship (forwarder quote + provider catalog — Operations pillar)
				"POST /v1/ship/quote",
				"GET /v1/ship/providers",
				// Seller diagnostics + tax
				"GET /v1/me/seller/privilege",
				"GET /v1/me/seller/kyc",
				"GET /v1/me/seller/subscription",
				"GET /v1/me/seller/payments-program",
				"GET /v1/me/seller/advertising-eligibility",
				"GET /v1/me/seller/sales-tax/{country}",
				"PUT|DELETE /v1/me/seller/sales-tax/{country}/{jurisdiction}",
				"GET /v1/me/seller/payout-settings",
				"POST /v1/me/seller/payout-settings/update-percentage",
				"GET /v1/me/seller/rate-tables/{id}",
				"POST /v1/me/seller/rate-tables/{id}/update-shipping-cost",
				"GET /v1/me/programs",
				"POST /v1/me/programs/opt-in",
				"POST /v1/me/programs/opt-out",
				"GET /v1/me/quota",
				"GET /v1/me/selling",
				"GET /v1/me/buying",
				// flipagent: keys (programmatic API key management)
				"GET /v1/keys/me",
				"POST /v1/keys/revoke",
				"GET /v1/keys/permissions",
				// flipagent: connect (programmatic eBay OAuth handshake)
				"GET /v1/connect/ebay",
				"GET /v1/connect/ebay/callback",
				"GET /v1/connect/ebay/status",
				"DELETE /v1/connect/ebay",
				// flipagent: billing (Stripe; session-driven)
				"POST /v1/billing/checkout",
				"POST /v1/billing/portal",
				"GET /v1/billing/invoices",
				"GET /v1/billing/quote",
				"GET|PUT /v1/billing/auto-recharge",
				"POST /v1/billing/webhook",
				// flipagent: dashboard (session-driven; /api/auth/* handled by Better-Auth)
				"GET /v1/me",
				"GET /v1/me/usage",
				"GET /v1/me/usage/breakdown",
				"GET /v1/me/usage/recent",
				"GET /v1/me/keys",
				"POST /v1/me/keys",
				"POST /v1/me/keys/{id}/reveal",
				"DELETE /v1/me/keys/{id}",
				"GET /v1/me/devices",
				"POST /v1/me/devices",
				"DELETE /v1/me/devices/{id}",
				"GET /v1/me/ebay/connect",
				"GET /v1/me/ebay/status",
				"DELETE /v1/me/ebay/connect",
				"GET /v1/me/permissions",
				"POST /v1/me/terms-acceptance",
				"DELETE /v1/me/account",
				"ALL /api/auth/*",
				// Notifications + webhooks
				"ALL /v1/notifications/*",
				"GET|POST|DELETE /v1/webhooks",
				// Agent (preview) + agent plumbing
				"POST /v1/agent/chat",
				"GET /v1/agent/sessions",
				"PATCH|DELETE /v1/agent/sessions/{id}",
				"GET|POST /v1/agent/rules",
				"DELETE /v1/agent/rules/{id}",
				"GET /v1/agent/runs",
				"ALL /v1/bridge/*",
				"POST /v1/browser/query",
				"POST /v1/browser/cookies",
				// Capabilities + health
				"GET /v1/capabilities",
				"GET /v1/health",
				// Admin (operator-only)
				"ALL /v1/admin/*",
				// flipagent: ToS hygiene + regulatory compliance
				"POST /v1/takedown",
				"POST /v1/takedown/counter-notice",
				// liveness + spec + MCP
				"GET /healthz",
				"GET /openapi.json",
				"GET /openapi.yaml",
				"ALL /mcp",
			],
		}),
);
