import type { TSchema } from "@sinclair/typebox";
import type { Config } from "../config.js";
import {
	adsAdBidUpdateDescription,
	adsAdBidUpdateExecute,
	adsAdBidUpdateInput,
	adsAdsListDescription,
	adsAdsListExecute,
	adsAdsListInput,
	adsBulkCreateDescription,
	adsBulkCreateExecute,
	adsBulkCreateInput,
	adsBulkDeleteDescription,
	adsBulkDeleteExecute,
	adsBulkDeleteInput,
	adsBulkUpdateBidDescription,
	adsBulkUpdateBidExecute,
	adsBulkUpdateBidInput,
	adsBulkUpdateStatusDescription,
	adsBulkUpdateStatusExecute,
	adsBulkUpdateStatusInput,
	adsCampaignByNameDescription,
	adsCampaignByNameExecute,
	adsCampaignByNameInput,
	adsCampaignCloneDescription,
	adsCampaignCloneExecute,
	adsCampaignCloneInput,
	adsCampaignEndDescription,
	adsCampaignEndExecute,
	adsCampaignEndInput,
	adsCampaignPauseDescription,
	adsCampaignPauseExecute,
	adsCampaignPauseInput,
	adsCampaignResumeDescription,
	adsCampaignResumeExecute,
	adsCampaignResumeInput,
	adsCampaignsCreateDescription,
	adsCampaignsCreateExecute,
	adsCampaignsCreateInput,
	adsCampaignsListDescription,
	adsCampaignsListExecute,
	adsCampaignsListInput,
	adsGroupsCreateDescription,
	adsGroupsCreateExecute,
	adsGroupsCreateInput,
	adsGroupsListDescription,
	adsGroupsListExecute,
	adsGroupsListInput,
	adsReportsCreateDescription,
	adsReportsCreateExecute,
	adsReportsCreateInput,
	adsReportsGetDescription,
	adsReportsGetExecute,
	adsReportsGetInput,
	adsReportsListDescription,
	adsReportsListExecute,
	adsReportsListInput,
	adsReportsMetadataDescription,
	adsReportsMetadataExecute,
	adsReportsMetadataInput,
} from "./ads.js";
import {
	bidsEligibleListingsDescription,
	bidsEligibleListingsExecute,
	bidsEligibleListingsInput,
	bidsListDescription,
	bidsListExecute,
	bidsListInput,
	bidsPlaceDescription,
	bidsPlaceExecute,
	bidsPlaceInput,
} from "./bids.js";
import { browserQueryDescription, browserQueryExecute, browserQueryInput } from "./browser-primitives.js";
import {
	disputesActivityDescription,
	disputesActivityExecute,
	disputesActivityInput,
	disputesGetDescription,
	disputesGetExecute,
	disputesGetInput,
	disputesListDescription,
	disputesListExecute,
	disputesListInput,
	disputesRespondDescription,
	disputesRespondExecute,
	disputesRespondInput,
} from "./disputes.js";
import {
	ebayBuyItemDescription,
	ebayBuyItemExecute,
	ebayBuyItemInput,
	ebayOrderCancelDescription,
	ebayOrderCancelExecute,
	ebayOrderCancelInput,
	ebayOrderStatusDescription,
	ebayOrderStatusExecute,
	ebayOrderStatusInput,
} from "./ebay-buy.js";
import { ebayItemDetailDescription, ebayItemDetailExecute, ebayItemDetailInput } from "./ebay-item-detail.js";
import {
	ebayCreateInventoryItemDescription,
	ebayCreateInventoryItemExecute,
	ebayCreateInventoryItemInput,
	ebayCreateOfferDescription,
	ebayCreateOfferExecute,
	ebayCreateOfferInput,
	ebayPublishOfferDescription,
	ebayPublishOfferExecute,
	ebayPublishOfferInput,
} from "./ebay-listings.js";
import { ebayListPayoutsDescription, ebayListPayoutsExecute, ebayListPayoutsInput } from "./ebay-payouts.js";
import {
	ebayListOrdersDescription,
	ebayListOrdersExecute,
	ebayListOrdersInput,
	ebayMarkShippedDescription,
	ebayMarkShippedExecute,
	ebayMarkShippedInput,
} from "./ebay-sales.js";
import { ebaySearchDescription, ebaySearchExecute, ebaySearchInput } from "./ebay-search.js";
import { ebaySoldSearchDescription, ebaySoldSearchExecute, ebaySoldSearchInput } from "./ebay-sold-search.js";
import {
	ebayTaxonomyAspectsDescription,
	ebayTaxonomyAspectsExecute,
	ebayTaxonomyAspectsInput,
	ebayTaxonomyDefaultIdDescription,
	ebayTaxonomyDefaultIdExecute,
	ebayTaxonomyDefaultIdInput,
	ebayTaxonomySuggestDescription,
	ebayTaxonomySuggestExecute,
	ebayTaxonomySuggestInput,
} from "./ebay-taxonomy.js";
import {
	evaluateJobDescription,
	evaluateJobExecute,
	evaluateJobInput,
	evaluateListingDescription,
	evaluateListingExecute,
	evaluateListingInput,
	evaluationPoolDescription,
	evaluationPoolExecute,
	evaluationPoolInput,
} from "./evaluate-listing.js";
import { expensesRecordDescription, expensesRecordExecute, expensesRecordInput } from "./expenses-record.js";
import { expensesSummaryDescription, expensesSummaryExecute, expensesSummaryInput } from "./expenses-summary.js";
import {
	feedbackAwaitingDescription,
	feedbackAwaitingExecute,
	feedbackAwaitingInput,
	feedbackLeaveDescription,
	feedbackLeaveExecute,
	feedbackLeaveInput,
	feedbackListDescription,
	feedbackListExecute,
	feedbackListInput,
} from "./feedback.js";
import {
	flipagentCapabilitiesDescription,
	flipagentCapabilitiesExecute,
	flipagentCapabilitiesInput,
} from "./flipagent-capabilities.js";
import {
	flipagentConnectStatusDescription,
	flipagentConnectStatusExecute,
	flipagentConnectStatusInput,
} from "./flipagent-connect.js";
import {
	planetExpressInventoryDescription,
	planetExpressInventoryExecute,
	planetExpressInventoryInput,
	planetExpressJobStatusDescription,
	planetExpressJobStatusExecute,
	planetExpressJobStatusInput,
	planetExpressLinkDescription,
	planetExpressLinkExecute,
	planetExpressLinkInput,
	planetExpressPackageDispatchDescription,
	planetExpressPackageDispatchExecute,
	planetExpressPackageDispatchInput,
	planetExpressPackagePhotosDescription,
	planetExpressPackagePhotosExecute,
	planetExpressPackagePhotosInput,
	planetExpressPackagesDescription,
	planetExpressPackagesExecute,
	planetExpressPackagesInput,
} from "./forwarder-planetexpress.js";
import { keysMeDescription, keysMeExecute, keysMeInput } from "./keys.js";
import {
	listingGroupsDeleteDescription,
	listingGroupsDeleteExecute,
	listingGroupsDeleteInput,
	listingGroupsGetDescription,
	listingGroupsGetExecute,
	listingGroupsGetInput,
	listingGroupsUpsertDescription,
	listingGroupsUpsertExecute,
	listingGroupsUpsertInput,
} from "./listing-groups.js";
import {
	listingsBulkGetInventoryDescription,
	listingsBulkGetInventoryExecute,
	listingsBulkGetInventoryInput,
	listingsBulkGetOffersDescription,
	listingsBulkGetOffersExecute,
	listingsBulkGetOffersInput,
	listingsBulkMigrateDescription,
	listingsBulkMigrateExecute,
	listingsBulkMigrateInput,
	listingsBulkPublishDescription,
	listingsBulkPublishExecute,
	listingsBulkPublishInput,
	listingsBulkUpdatePricesDescription,
	listingsBulkUpdatePricesExecute,
	listingsBulkUpdatePricesInput,
	listingsBulkUpsertDescription,
	listingsBulkUpsertExecute,
	listingsBulkUpsertInput,
} from "./listings-bulk.js";
import {
	listingsPreviewFeesDescription,
	listingsPreviewFeesExecute,
	listingsPreviewFeesInput,
} from "./listings-fees.js";
import {
	listingsCompatibilityDeleteDescription,
	listingsCompatibilityDeleteExecute,
	listingsCompatibilityDeleteInput,
	listingsCompatibilityGetDescription,
	listingsCompatibilityGetExecute,
	listingsCompatibilityGetInput,
	listingsCompatibilitySetDescription,
	listingsCompatibilitySetExecute,
	listingsCompatibilitySetInput,
	listingsGroupPublishDescription,
	listingsGroupPublishExecute,
	listingsGroupPublishInput,
	listingsGroupWithdrawDescription,
	listingsGroupWithdrawExecute,
	listingsGroupWithdrawInput,
} from "./listings-groups.js";
import {
	locationsDeleteDescription,
	locationsDeleteExecute,
	locationsDeleteInput,
	locationsDisableDescription,
	locationsDisableExecute,
	locationsDisableInput,
	locationsEnableDescription,
	locationsEnableExecute,
	locationsEnableInput,
	locationsGetDescription,
	locationsGetExecute,
	locationsGetInput,
	locationsListDescription,
	locationsListExecute,
	locationsListInput,
	locationsUpsertDescription,
	locationsUpsertExecute,
	locationsUpsertInput,
} from "./locations.js";
import {
	markdownsCreateDescription,
	markdownsCreateExecute,
	markdownsCreateInput,
	markdownsListDescription,
	markdownsListExecute,
	markdownsListInput,
} from "./markdowns.js";
import {
	mePrograms_listDescription,
	mePrograms_listExecute,
	mePrograms_listInput,
	mePrograms_optInDescription,
	mePrograms_optInExecute,
	mePrograms_optInInput,
	mePrograms_optOutDescription,
	mePrograms_optOutExecute,
	mePrograms_optOutInput,
	meQuotaDescription,
	meQuotaExecute,
	meQuotaInput,
} from "./me-account.js";
import {
	mediaCreateUploadDescription,
	mediaCreateUploadExecute,
	mediaCreateUploadInput,
	mediaGetDescription,
	mediaGetExecute,
	mediaGetInput,
} from "./media.js";
import {
	conversationsListDescription,
	conversationsListExecute,
	conversationsListInput,
	conversationThreadDescription,
	conversationThreadExecute,
	conversationThreadInput,
	messagesSendDescription,
	messagesSendExecute,
	messagesSendInput,
} from "./messages.js";
import {
	notificationsConfigGetDescription,
	notificationsConfigGetExecute,
	notificationsConfigGetInput,
	notificationsConfigUpdateDescription,
	notificationsConfigUpdateExecute,
	notificationsConfigUpdateInput,
	notificationsDestinationsDescription,
	notificationsDestinationsExecute,
	notificationsDestinationsInput,
	notificationsPublicKeyDescription,
	notificationsPublicKeyExecute,
	notificationsPublicKeyInput,
	notificationsRecentDescription,
	notificationsRecentExecute,
	notificationsRecentInput,
	notificationsSubAddFilterDescription,
	notificationsSubAddFilterExecute,
	notificationsSubAddFilterInput,
	notificationsSubDeleteFilterDescription,
	notificationsSubDeleteFilterExecute,
	notificationsSubDeleteFilterInput,
	notificationsSubDisableDescription,
	notificationsSubDisableExecute,
	notificationsSubDisableInput,
	notificationsSubEnableDescription,
	notificationsSubEnableExecute,
	notificationsSubEnableInput,
	notificationsSubscriptionsCreateDescription,
	notificationsSubscriptionsCreateExecute,
	notificationsSubscriptionsCreateInput,
	notificationsSubscriptionsDeleteDescription,
	notificationsSubscriptionsDeleteExecute,
	notificationsSubscriptionsDeleteInput,
	notificationsSubscriptionsGetDescription,
	notificationsSubscriptionsGetExecute,
	notificationsSubscriptionsGetInput,
	notificationsSubscriptionsListDescription,
	notificationsSubscriptionsListExecute,
	notificationsSubscriptionsListInput,
	notificationsSubTestDescription,
	notificationsSubTestExecute,
	notificationsSubTestInput,
	notificationsTopicsDescription,
	notificationsTopicsExecute,
	notificationsTopicsInput,
} from "./notifications.js";
import {
	offersCreateDescription,
	offersCreateExecute,
	offersCreateInput,
	offersEligibleListingsDescription,
	offersEligibleListingsExecute,
	offersEligibleListingsInput,
	offersListDescription,
	offersListExecute,
	offersListInput,
	offersRespondDescription,
	offersRespondExecute,
	offersRespondInput,
} from "./offers.js";
import {
	policiesListByTypeDescription,
	policiesListByTypeExecute,
	policiesListByTypeInput,
	policiesListDescription,
	policiesListExecute,
	policiesListInput,
} from "./policies.js";
import {
	promotionsCreateDescription,
	promotionsCreateExecute,
	promotionsCreateInput,
	promotionsListDescription,
	promotionsListExecute,
	promotionsListInput,
	promotionsReportsCreateDescription,
	promotionsReportsCreateExecute,
	promotionsReportsCreateInput,
	promotionsReportsGetDescription,
	promotionsReportsGetExecute,
	promotionsReportsGetInput,
	promotionsReportsListDescription,
	promotionsReportsListExecute,
	promotionsReportsListInput,
} from "./promotions.js";
import {
	recommendationsListDescription,
	recommendationsListExecute,
	recommendationsListInput,
} from "./recommendations.js";
import {
	savedSearchesCreateDescription,
	savedSearchesCreateExecute,
	savedSearchesCreateInput,
	savedSearchesDeleteDescription,
	savedSearchesDeleteExecute,
	savedSearchesDeleteInput,
	savedSearchesListDescription,
	savedSearchesListExecute,
	savedSearchesListInput,
} from "./saved-searches.js";
import {
	sellerAdvertisingEligibilityDescription,
	sellerAdvertisingEligibilityExecute,
	sellerAdvertisingEligibilityInput,
	sellerEligibilityDescription,
	sellerEligibilityExecute,
	sellerEligibilityInput,
	sellerKycDescription,
	sellerKycExecute,
	sellerKycInput,
	sellerPaymentsProgramDescription,
	sellerPaymentsProgramExecute,
	sellerPaymentsProgramInput,
	sellerPrivilegeDescription,
	sellerPrivilegeExecute,
	sellerPrivilegeInput,
	sellerSalesTaxDescription,
	sellerSalesTaxExecute,
	sellerSalesTaxInput,
	sellerSubscriptionDescription,
	sellerSubscriptionExecute,
	sellerSubscriptionInput,
} from "./seller.js";
import { shipProvidersDescription, shipProvidersExecute, shipProvidersInput } from "./ship-providers.js";
import { shipQuoteDescription, shipQuoteExecute, shipQuoteInput } from "./ship-quote.js";
import {
	storeCategoriesDescription,
	storeCategoriesExecute,
	storeCategoriesInput,
	storeCategoriesUpsertDescription,
	storeCategoriesUpsertExecute,
	storeCategoriesUpsertInput,
} from "./store.js";
import { transactionsListDescription, transactionsListExecute, transactionsListInput } from "./transactions.js";
import { translateDescription, translateExecute, translateInput } from "./translate.js";
import { trendsCategoriesDescription, trendsCategoriesExecute, trendsCategoriesInput } from "./trends.js";
import {
	watchingListDescription,
	watchingListExecute,
	watchingListInput,
	watchingUnwatchDescription,
	watchingUnwatchExecute,
	watchingUnwatchInput,
	watchingWatchDescription,
	watchingWatchExecute,
	watchingWatchInput,
} from "./watching.js";
import {
	webhooksListDescription,
	webhooksListExecute,
	webhooksListInput,
	webhooksRegisterDescription,
	webhooksRegisterExecute,
	webhooksRegisterInput,
	webhooksRevokeDescription,
	webhooksRevokeExecute,
	webhooksRevokeInput,
} from "./webhooks.js";

/**
 * Toolsets group ~108 tools so the host (Claude Desktop, Cursor, etc.) can
 * load only the slice the user actually needs. Cursor caps at 40 MCP tools
 * total; Anthropic notes selection accuracy degrades past 30–50. The default
 * slice ("core") is kept under the 40-tool ceiling. Opt in to others via
 * `FLIPAGENT_MCP_TOOLSETS=core,marketing,bulk,…`. Pattern follows GitHub's
 * official MCP server.
 */
export type Toolset =
	| "core" // sourcing + decisions + buy + listing prereqs + sale fulfillment + finance — default-on
	| "comms" // messages + offers + disputes + feedback (post-sale buyer comms)
	| "marketing" // promotions + markdowns + ads + store
	| "bulk" // listings_bulk + listing_groups (power-user batch ops)
	| "forwarder" // /v1/forwarder/{provider}/* (Planet Express today)
	| "discovery" // watching + saved_searches + recommendations + trends + bids
	| "seller_account" // /v1/me/seller/* read-only diagnostics
	| "notifications" // webhooks + eBay platform notifications + browser_query
	| "admin"; // bridge surfaces, key introspection, status

export const ALL_TOOLSETS: readonly Toolset[] = [
	"core",
	"comms",
	"marketing",
	"bulk",
	"forwarder",
	"discovery",
	"seller_account",
	"notifications",
	"admin",
] as const;

export const DEFAULT_TOOLSETS: readonly Toolset[] = ["core", "admin"] as const;

export interface Tool {
	name: string;
	description: string;
	inputSchema: TSchema;
	execute: (config: Config, args: Record<string, unknown>) => Promise<unknown>;
	toolset: Toolset;
}

/**
 * Tool naming convention: `flipagent_<verb>_<resource>`, snake_case. Per
 * Anthropic's MCP-builder skill (anthropics/skills `mcp_best_practices.md`)
 * and the GitHub / Stripe / Slack reference servers, action-leading names
 * (`create_listing` over `listings_create`) align better with how LLMs plan
 * tool calls. The `flipagent_` prefix keeps names collision-free when other
 * MCP servers are loaded alongside. Marketplace stays a *parameter*, never
 * part of the tool name — Amazon/Mercari adapters reuse the same names.
 *
 * Verb vocabulary: list, get, search, create, update, upsert, delete,
 * enable, disable, ship, quote, evaluate, buy, cancel, place, watch,
 * unwatch, leave, send, respond, register, revoke, refresh, dispatch,
 * link, record, suggest, relist, publish, migrate, bulk_*.
 */
export const tools: Tool[] = [
	// ─── core ────────────────────────────────────────────────────────────
	// First-call discovery + key introspection.
	{
		name: "flipagent_get_capabilities",
		description: flipagentCapabilitiesDescription,
		inputSchema: flipagentCapabilitiesInput,
		execute: flipagentCapabilitiesExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_my_key",
		description: keysMeDescription,
		inputSchema: keysMeInput,
		execute: keysMeExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_quota",
		description: meQuotaDescription,
		inputSchema: meQuotaInput,
		execute: meQuotaExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_programs",
		description: mePrograms_listDescription,
		inputSchema: mePrograms_listInput,
		execute: mePrograms_listExecute,
		toolset: "core",
	},
	{
		name: "flipagent_opt_in_program",
		description: mePrograms_optInDescription,
		inputSchema: mePrograms_optInInput,
		execute: mePrograms_optInExecute,
		toolset: "core",
	},
	{
		name: "flipagent_opt_out_program",
		description: mePrograms_optOutDescription,
		inputSchema: mePrograms_optOutInput,
		execute: mePrograms_optOutExecute,
		toolset: "core",
	},
	{
		name: "flipagent_translate",
		description: translateDescription,
		inputSchema: translateInput,
		execute: translateExecute,
		toolset: "core",
	},

	// Sourcing — marketplace data (anonymous app token works)
	{
		name: "flipagent_search_items",
		description: ebaySearchDescription,
		inputSchema: ebaySearchInput,
		execute: ebaySearchExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_item",
		description: ebayItemDetailDescription,
		inputSchema: ebayItemDetailInput,
		execute: ebayItemDetailExecute,
		toolset: "core",
	},
	{
		name: "flipagent_search_sold_items",
		description: ebaySoldSearchDescription,
		inputSchema: ebaySoldSearchInput,
		execute: ebaySoldSearchExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_categories",
		description: ebayTaxonomyDefaultIdDescription,
		inputSchema: ebayTaxonomyDefaultIdInput,
		execute: ebayTaxonomyDefaultIdExecute,
		toolset: "core",
	},
	{
		name: "flipagent_suggest_category",
		description: ebayTaxonomySuggestDescription,
		inputSchema: ebayTaxonomySuggestInput,
		execute: ebayTaxonomySuggestExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_category_aspects",
		description: ebayTaxonomyAspectsDescription,
		inputSchema: ebayTaxonomyAspectsInput,
		execute: ebayTaxonomyAspectsExecute,
		toolset: "core",
	},

	// Decisions + Operations — flipagent value-add
	{
		name: "flipagent_evaluate_item",
		description: evaluateListingDescription,
		inputSchema: evaluateListingInput,
		execute: evaluateListingExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_evaluate_job",
		description: evaluateJobDescription,
		inputSchema: evaluateJobInput,
		execute: evaluateJobExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_evaluation_pool",
		description: evaluationPoolDescription,
		inputSchema: evaluationPoolInput,
		execute: evaluationPoolExecute,
		toolset: "core",
	},
	{
		name: "flipagent_quote_shipping",
		description: shipQuoteDescription,
		inputSchema: shipQuoteInput,
		execute: shipQuoteExecute,
		toolset: "core",
	},

	// Buying (extension-bridged or REST passthrough)
	{
		name: "flipagent_create_purchase",
		description: ebayBuyItemDescription,
		inputSchema: ebayBuyItemInput,
		execute: ebayBuyItemExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_purchase",
		description: ebayOrderStatusDescription,
		inputSchema: ebayOrderStatusInput,
		execute: ebayOrderStatusExecute,
		toolset: "core",
	},
	{
		name: "flipagent_cancel_purchase",
		description: ebayOrderCancelDescription,
		inputSchema: ebayOrderCancelInput,
		execute: ebayOrderCancelExecute,
		toolset: "core",
	},

	// Listing prereqs + listing CRUD (sell-side, eBay OAuth required)
	{
		name: "flipagent_create_media_upload",
		description: mediaCreateUploadDescription,
		inputSchema: mediaCreateUploadInput,
		execute: mediaCreateUploadExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_media",
		description: mediaGetDescription,
		inputSchema: mediaGetInput,
		execute: mediaGetExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_policies",
		description: policiesListDescription,
		inputSchema: policiesListInput,
		execute: policiesListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_policies_by_type",
		description: policiesListByTypeDescription,
		inputSchema: policiesListByTypeInput,
		execute: policiesListByTypeExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_locations",
		description: locationsListDescription,
		inputSchema: locationsListInput,
		execute: locationsListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_upsert_location",
		description: locationsUpsertDescription,
		inputSchema: locationsUpsertInput,
		execute: locationsUpsertExecute,
		toolset: "core",
	},
	{
		name: "flipagent_create_listing",
		description: ebayCreateInventoryItemDescription,
		inputSchema: ebayCreateInventoryItemInput,
		execute: ebayCreateInventoryItemExecute,
		toolset: "core",
	},
	{
		name: "flipagent_update_listing",
		description: ebayCreateOfferDescription,
		inputSchema: ebayCreateOfferInput,
		execute: ebayCreateOfferExecute,
		toolset: "core",
	},
	{
		name: "flipagent_relist_listing",
		description: ebayPublishOfferDescription,
		inputSchema: ebayPublishOfferInput,
		execute: ebayPublishOfferExecute,
		toolset: "core",
	},
	{
		name: "flipagent_preview_listing_fees",
		description: listingsPreviewFeesDescription,
		inputSchema: listingsPreviewFeesInput,
		execute: listingsPreviewFeesExecute,
		toolset: "core",
	},
	{
		name: "flipagent_publish_listing_group",
		description: listingsGroupPublishDescription,
		inputSchema: listingsGroupPublishInput,
		execute: listingsGroupPublishExecute,
		toolset: "core",
	},
	{
		name: "flipagent_withdraw_listing_group",
		description: listingsGroupWithdrawDescription,
		inputSchema: listingsGroupWithdrawInput,
		execute: listingsGroupWithdrawExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_listing_compatibility",
		description: listingsCompatibilityGetDescription,
		inputSchema: listingsCompatibilityGetInput,
		execute: listingsCompatibilityGetExecute,
		toolset: "core",
	},
	{
		name: "flipagent_set_listing_compatibility",
		description: listingsCompatibilitySetDescription,
		inputSchema: listingsCompatibilitySetInput,
		execute: listingsCompatibilitySetExecute,
		toolset: "core",
	},
	{
		name: "flipagent_delete_listing_compatibility",
		description: listingsCompatibilityDeleteDescription,
		inputSchema: listingsCompatibilityDeleteInput,
		execute: listingsCompatibilityDeleteExecute,
		toolset: "core",
	},

	// Sale fulfillment + finance (sell-side)
	{
		name: "flipagent_list_sales",
		description: ebayListOrdersDescription,
		inputSchema: ebayListOrdersInput,
		execute: ebayListOrdersExecute,
		toolset: "core",
	},
	{
		name: "flipagent_ship_sale",
		description: ebayMarkShippedDescription,
		inputSchema: ebayMarkShippedInput,
		execute: ebayMarkShippedExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_payouts",
		description: ebayListPayoutsDescription,
		inputSchema: ebayListPayoutsInput,
		execute: ebayListPayoutsExecute,
		toolset: "core",
	},
	{
		name: "flipagent_list_transactions",
		description: transactionsListDescription,
		inputSchema: transactionsListInput,
		execute: transactionsListExecute,
		toolset: "core",
	},
	{
		name: "flipagent_record_expense",
		description: expensesRecordDescription,
		inputSchema: expensesRecordInput,
		execute: expensesRecordExecute,
		toolset: "core",
	},
	{
		name: "flipagent_get_expense_summary",
		description: expensesSummaryDescription,
		inputSchema: expensesSummaryInput,
		execute: expensesSummaryExecute,
		toolset: "core",
	},

	// ─── admin ───────────────────────────────────────────────────────────
	// Connection status, ship providers, location-state toggles, location detail/delete.
	{
		name: "flipagent_get_ebay_connection",
		description: flipagentConnectStatusDescription,
		inputSchema: flipagentConnectStatusInput,
		execute: flipagentConnectStatusExecute,
		toolset: "admin",
	},
	{
		name: "flipagent_list_shipping_providers",
		description: shipProvidersDescription,
		inputSchema: shipProvidersInput,
		execute: shipProvidersExecute,
		toolset: "admin",
	},
	{
		name: "flipagent_get_location",
		description: locationsGetDescription,
		inputSchema: locationsGetInput,
		execute: locationsGetExecute,
		toolset: "admin",
	},
	{
		name: "flipagent_delete_location",
		description: locationsDeleteDescription,
		inputSchema: locationsDeleteInput,
		execute: locationsDeleteExecute,
		toolset: "admin",
	},
	{
		name: "flipagent_enable_location",
		description: locationsEnableDescription,
		inputSchema: locationsEnableInput,
		execute: locationsEnableExecute,
		toolset: "admin",
	},
	{
		name: "flipagent_disable_location",
		description: locationsDisableDescription,
		inputSchema: locationsDisableInput,
		execute: locationsDisableExecute,
		toolset: "admin",
	},

	// ─── comms (post-sale buyer turnover) ────────────────────────────────
	{
		name: "flipagent_list_conversations",
		description: conversationsListDescription,
		inputSchema: conversationsListInput,
		execute: conversationsListExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_get_conversation_thread",
		description: conversationThreadDescription,
		inputSchema: conversationThreadInput,
		execute: conversationThreadExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_send_message",
		description: messagesSendDescription,
		inputSchema: messagesSendInput,
		execute: messagesSendExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_offers",
		description: offersListDescription,
		inputSchema: offersListInput,
		execute: offersListExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_create_offer",
		description: offersCreateDescription,
		inputSchema: offersCreateInput,
		execute: offersCreateExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_offer_eligible_listings",
		description: offersEligibleListingsDescription,
		inputSchema: offersEligibleListingsInput,
		execute: offersEligibleListingsExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_respond_to_offer",
		description: offersRespondDescription,
		inputSchema: offersRespondInput,
		execute: offersRespondExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_disputes",
		description: disputesListDescription,
		inputSchema: disputesListInput,
		execute: disputesListExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_get_dispute",
		description: disputesGetDescription,
		inputSchema: disputesGetInput,
		execute: disputesGetExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_respond_to_dispute",
		description: disputesRespondDescription,
		inputSchema: disputesRespondInput,
		execute: disputesRespondExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_get_dispute_activity",
		description: disputesActivityDescription,
		inputSchema: disputesActivityInput,
		execute: disputesActivityExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_feedback",
		description: feedbackListDescription,
		inputSchema: feedbackListInput,
		execute: feedbackListExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_list_awaiting_feedback",
		description: feedbackAwaitingDescription,
		inputSchema: feedbackAwaitingInput,
		execute: feedbackAwaitingExecute,
		toolset: "comms",
	},
	{
		name: "flipagent_leave_feedback",
		description: feedbackLeaveDescription,
		inputSchema: feedbackLeaveInput,
		execute: feedbackLeaveExecute,
		toolset: "comms",
	},

	// ─── marketing (promotions, markdowns, ads, store) ───────────────────
	{
		name: "flipagent_list_promotions",
		description: promotionsListDescription,
		inputSchema: promotionsListInput,
		execute: promotionsListExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_create_promotion",
		description: promotionsCreateDescription,
		inputSchema: promotionsCreateInput,
		execute: promotionsCreateExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_list_promotion_reports",
		description: promotionsReportsListDescription,
		inputSchema: promotionsReportsListInput,
		execute: promotionsReportsListExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_create_promotion_report",
		description: promotionsReportsCreateDescription,
		inputSchema: promotionsReportsCreateInput,
		execute: promotionsReportsCreateExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_get_promotion_report",
		description: promotionsReportsGetDescription,
		inputSchema: promotionsReportsGetInput,
		execute: promotionsReportsGetExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_list_markdowns",
		description: markdownsListDescription,
		inputSchema: markdownsListInput,
		execute: markdownsListExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_create_markdown",
		description: markdownsCreateDescription,
		inputSchema: markdownsCreateInput,
		execute: markdownsCreateExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_list_ad_campaigns",
		description: adsCampaignsListDescription,
		inputSchema: adsCampaignsListInput,
		execute: adsCampaignsListExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_create_ad_campaign",
		description: adsCampaignsCreateDescription,
		inputSchema: adsCampaignsCreateInput,
		execute: adsCampaignsCreateExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_list_ads",
		description: adsAdsListDescription,
		inputSchema: adsAdsListInput,
		execute: adsAdsListExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_list_ad_groups",
		description: adsGroupsListDescription,
		inputSchema: adsGroupsListInput,
		execute: adsGroupsListExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_create_ad_group",
		description: adsGroupsCreateDescription,
		inputSchema: adsGroupsCreateInput,
		execute: adsGroupsCreateExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_get_ad_report_metadata",
		description: adsReportsMetadataDescription,
		inputSchema: adsReportsMetadataInput,
		execute: adsReportsMetadataExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_list_ad_reports",
		description: adsReportsListDescription,
		inputSchema: adsReportsListInput,
		execute: adsReportsListExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_create_ad_report",
		description: adsReportsCreateDescription,
		inputSchema: adsReportsCreateInput,
		execute: adsReportsCreateExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_get_ad_report",
		description: adsReportsGetDescription,
		inputSchema: adsReportsGetInput,
		execute: adsReportsGetExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_get_ad_campaign_by_name",
		description: adsCampaignByNameDescription,
		inputSchema: adsCampaignByNameInput,
		execute: adsCampaignByNameExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_pause_ad_campaign",
		description: adsCampaignPauseDescription,
		inputSchema: adsCampaignPauseInput,
		execute: adsCampaignPauseExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_resume_ad_campaign",
		description: adsCampaignResumeDescription,
		inputSchema: adsCampaignResumeInput,
		execute: adsCampaignResumeExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_end_ad_campaign",
		description: adsCampaignEndDescription,
		inputSchema: adsCampaignEndInput,
		execute: adsCampaignEndExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_clone_ad_campaign",
		description: adsCampaignCloneDescription,
		inputSchema: adsCampaignCloneInput,
		execute: adsCampaignCloneExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_update_ad_bid",
		description: adsAdBidUpdateDescription,
		inputSchema: adsAdBidUpdateInput,
		execute: adsAdBidUpdateExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_bulk_create_ads",
		description: adsBulkCreateDescription,
		inputSchema: adsBulkCreateInput,
		execute: adsBulkCreateExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_bulk_update_ad_bids",
		description: adsBulkUpdateBidDescription,
		inputSchema: adsBulkUpdateBidInput,
		execute: adsBulkUpdateBidExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_bulk_delete_ads",
		description: adsBulkDeleteDescription,
		inputSchema: adsBulkDeleteInput,
		execute: adsBulkDeleteExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_bulk_update_ad_status",
		description: adsBulkUpdateStatusDescription,
		inputSchema: adsBulkUpdateStatusInput,
		execute: adsBulkUpdateStatusExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_list_store_categories",
		description: storeCategoriesDescription,
		inputSchema: storeCategoriesInput,
		execute: storeCategoriesExecute,
		toolset: "marketing",
	},
	{
		name: "flipagent_upsert_store_categories",
		description: storeCategoriesUpsertDescription,
		inputSchema: storeCategoriesUpsertInput,
		execute: storeCategoriesUpsertExecute,
		toolset: "marketing",
	},

	// ─── bulk (variations + power-user batch) ────────────────────────────
	{
		name: "flipagent_get_listing_group",
		description: listingGroupsGetDescription,
		inputSchema: listingGroupsGetInput,
		execute: listingGroupsGetExecute,
		toolset: "bulk",
	},
	{
		name: "flipagent_upsert_listing_group",
		description: listingGroupsUpsertDescription,
		inputSchema: listingGroupsUpsertInput,
		execute: listingGroupsUpsertExecute,
		toolset: "bulk",
	},
	{
		name: "flipagent_delete_listing_group",
		description: listingGroupsDeleteDescription,
		inputSchema: listingGroupsDeleteInput,
		execute: listingGroupsDeleteExecute,
		toolset: "bulk",
	},
	{
		name: "flipagent_bulk_get_inventory",
		description: listingsBulkGetInventoryDescription,
		inputSchema: listingsBulkGetInventoryInput,
		execute: listingsBulkGetInventoryExecute,
		toolset: "bulk",
	},
	{
		name: "flipagent_bulk_get_offers",
		description: listingsBulkGetOffersDescription,
		inputSchema: listingsBulkGetOffersInput,
		execute: listingsBulkGetOffersExecute,
		toolset: "bulk",
	},
	{
		name: "flipagent_bulk_update_listing_prices",
		description: listingsBulkUpdatePricesDescription,
		inputSchema: listingsBulkUpdatePricesInput,
		execute: listingsBulkUpdatePricesExecute,
		toolset: "bulk",
	},
	{
		name: "flipagent_bulk_upsert_listings",
		description: listingsBulkUpsertDescription,
		inputSchema: listingsBulkUpsertInput,
		execute: listingsBulkUpsertExecute,
		toolset: "bulk",
	},
	{
		name: "flipagent_bulk_publish_listings",
		description: listingsBulkPublishDescription,
		inputSchema: listingsBulkPublishInput,
		execute: listingsBulkPublishExecute,
		toolset: "bulk",
	},
	{
		name: "flipagent_bulk_migrate_listings",
		description: listingsBulkMigrateDescription,
		inputSchema: listingsBulkMigrateInput,
		execute: listingsBulkMigrateExecute,
		toolset: "bulk",
	},

	// ─── forwarder ───────────────────────────────────────────────────────
	{
		name: "flipagent_refresh_forwarder",
		description: planetExpressPackagesDescription,
		inputSchema: planetExpressPackagesInput,
		execute: planetExpressPackagesExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_list_forwarder_inventory",
		description: planetExpressInventoryDescription,
		inputSchema: planetExpressInventoryInput,
		execute: planetExpressInventoryExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_request_package_photos",
		description: planetExpressPackagePhotosDescription,
		inputSchema: planetExpressPackagePhotosInput,
		execute: planetExpressPackagePhotosExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_dispatch_package",
		description: planetExpressPackageDispatchDescription,
		inputSchema: planetExpressPackageDispatchInput,
		execute: planetExpressPackageDispatchExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_link_package",
		description: planetExpressLinkDescription,
		inputSchema: planetExpressLinkInput,
		execute: planetExpressLinkExecute,
		toolset: "forwarder",
	},
	{
		name: "flipagent_get_forwarder_job",
		description: planetExpressJobStatusDescription,
		inputSchema: planetExpressJobStatusInput,
		execute: planetExpressJobStatusExecute,
		toolset: "forwarder",
	},

	// ─── discovery (sourcing radar) ──────────────────────────────────────
	{
		name: "flipagent_list_watching",
		description: watchingListDescription,
		inputSchema: watchingListInput,
		execute: watchingListExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_watch_item",
		description: watchingWatchDescription,
		inputSchema: watchingWatchInput,
		execute: watchingWatchExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_unwatch_item",
		description: watchingUnwatchDescription,
		inputSchema: watchingUnwatchInput,
		execute: watchingUnwatchExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_list_saved_searches",
		description: savedSearchesListDescription,
		inputSchema: savedSearchesListInput,
		execute: savedSearchesListExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_create_saved_search",
		description: savedSearchesCreateDescription,
		inputSchema: savedSearchesCreateInput,
		execute: savedSearchesCreateExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_delete_saved_search",
		description: savedSearchesDeleteDescription,
		inputSchema: savedSearchesDeleteInput,
		execute: savedSearchesDeleteExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_get_category_trends",
		description: trendsCategoriesDescription,
		inputSchema: trendsCategoriesInput,
		execute: trendsCategoriesExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_list_recommendations",
		description: recommendationsListDescription,
		inputSchema: recommendationsListInput,
		execute: recommendationsListExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_list_bids",
		description: bidsListDescription,
		inputSchema: bidsListInput,
		execute: bidsListExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_place_bid",
		description: bidsPlaceDescription,
		inputSchema: bidsPlaceInput,
		execute: bidsPlaceExecute,
		toolset: "discovery",
	},
	{
		name: "flipagent_list_biddable_listings",
		description: bidsEligibleListingsDescription,
		inputSchema: bidsEligibleListingsInput,
		execute: bidsEligibleListingsExecute,
		toolset: "discovery",
	},

	// ─── seller_account (read-only diagnostics) ──────────────────────────
	{
		name: "flipagent_get_seller_eligibility",
		description: sellerEligibilityDescription,
		inputSchema: sellerEligibilityInput,
		execute: sellerEligibilityExecute,
		toolset: "seller_account",
	},
	{
		name: "flipagent_get_seller_privilege",
		description: sellerPrivilegeDescription,
		inputSchema: sellerPrivilegeInput,
		execute: sellerPrivilegeExecute,
		toolset: "seller_account",
	},
	{
		name: "flipagent_get_seller_kyc",
		description: sellerKycDescription,
		inputSchema: sellerKycInput,
		execute: sellerKycExecute,
		toolset: "seller_account",
	},
	{
		name: "flipagent_get_seller_subscription",
		description: sellerSubscriptionDescription,
		inputSchema: sellerSubscriptionInput,
		execute: sellerSubscriptionExecute,
		toolset: "seller_account",
	},
	{
		name: "flipagent_get_seller_payments_program",
		description: sellerPaymentsProgramDescription,
		inputSchema: sellerPaymentsProgramInput,
		execute: sellerPaymentsProgramExecute,
		toolset: "seller_account",
	},
	{
		name: "flipagent_get_seller_advertising_eligibility",
		description: sellerAdvertisingEligibilityDescription,
		inputSchema: sellerAdvertisingEligibilityInput,
		execute: sellerAdvertisingEligibilityExecute,
		toolset: "seller_account",
	},
	{
		name: "flipagent_get_seller_sales_tax",
		description: sellerSalesTaxDescription,
		inputSchema: sellerSalesTaxInput,
		execute: sellerSalesTaxExecute,
		toolset: "seller_account",
	},

	// ─── notifications + browser DOM primitive ───────────────────────────
	{
		name: "flipagent_register_webhook",
		description: webhooksRegisterDescription,
		inputSchema: webhooksRegisterInput,
		execute: webhooksRegisterExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_webhooks",
		description: webhooksListDescription,
		inputSchema: webhooksListInput,
		execute: webhooksListExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_revoke_webhook",
		description: webhooksRevokeDescription,
		inputSchema: webhooksRevokeInput,
		execute: webhooksRevokeExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_notification_topics",
		description: notificationsTopicsDescription,
		inputSchema: notificationsTopicsInput,
		execute: notificationsTopicsExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_notification_destinations",
		description: notificationsDestinationsDescription,
		inputSchema: notificationsDestinationsInput,
		execute: notificationsDestinationsExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_notification_subscriptions",
		description: notificationsSubscriptionsListDescription,
		inputSchema: notificationsSubscriptionsListInput,
		execute: notificationsSubscriptionsListExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_create_notification_subscription",
		description: notificationsSubscriptionsCreateDescription,
		inputSchema: notificationsSubscriptionsCreateInput,
		execute: notificationsSubscriptionsCreateExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_get_notification_subscription",
		description: notificationsSubscriptionsGetDescription,
		inputSchema: notificationsSubscriptionsGetInput,
		execute: notificationsSubscriptionsGetExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_delete_notification_subscription",
		description: notificationsSubscriptionsDeleteDescription,
		inputSchema: notificationsSubscriptionsDeleteInput,
		execute: notificationsSubscriptionsDeleteExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_enable_notification_subscription",
		description: notificationsSubEnableDescription,
		inputSchema: notificationsSubEnableInput,
		execute: notificationsSubEnableExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_disable_notification_subscription",
		description: notificationsSubDisableDescription,
		inputSchema: notificationsSubDisableInput,
		execute: notificationsSubDisableExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_test_notification_subscription",
		description: notificationsSubTestDescription,
		inputSchema: notificationsSubTestInput,
		execute: notificationsSubTestExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_add_notification_filter",
		description: notificationsSubAddFilterDescription,
		inputSchema: notificationsSubAddFilterInput,
		execute: notificationsSubAddFilterExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_delete_notification_filter",
		description: notificationsSubDeleteFilterDescription,
		inputSchema: notificationsSubDeleteFilterInput,
		execute: notificationsSubDeleteFilterExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_get_notification_config",
		description: notificationsConfigGetDescription,
		inputSchema: notificationsConfigGetInput,
		execute: notificationsConfigGetExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_update_notification_config",
		description: notificationsConfigUpdateDescription,
		inputSchema: notificationsConfigUpdateInput,
		execute: notificationsConfigUpdateExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_get_notification_public_key",
		description: notificationsPublicKeyDescription,
		inputSchema: notificationsPublicKeyInput,
		execute: notificationsPublicKeyExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_list_recent_notifications",
		description: notificationsRecentDescription,
		inputSchema: notificationsRecentInput,
		execute: notificationsRecentExecute,
		toolset: "notifications",
	},
	{
		name: "flipagent_query_browser",
		description: browserQueryDescription,
		inputSchema: browserQueryInput,
		execute: browserQueryExecute,
		toolset: "notifications",
	},
];

/**
 * Filter the registry by toolsets enabled for this MCP instance.
 * Pass `["*"]` to enable all. Default = `DEFAULT_TOOLSETS`.
 */
export function selectTools(enabled: readonly Toolset[] | readonly ["*"]): Tool[] {
	if (enabled.length === 1 && enabled[0] === "*") return tools;
	const set = new Set(enabled as readonly Toolset[]);
	return tools.filter((t) => set.has(t.toolset));
}
